### PR TITLE
Add disposable emails

### PR DESCRIPTION
**Pull request by rynmccrmck**
Adding domains from https://github.com/disposable/disposable-email-domains. Found this while searching for missing domains from email-fake.com.

### CODE REVIEW

**Comment by rynmccrmck** [comment]
Opened in [source repo](https://github.com/ivolo/disposable-email-domains/pull/944) in case this is preferred.

**Comment by lryong** [comment]
@rynmccrmck  Thanks for the PR, disposable domains data will be confirmed in the near future, I will also track whether the source repo will be updated, if the data is verified to be OK, I will merge this PR

**Comment by rynmccrmck** [comment]
> @rynmccrmck Thanks for the PR, disposable domains data will be confirmed in the near future, I will also track whether the source repo will be updated, if the data is verified to be OK, I will merge this PR

Thanks @lryong, anything I can do to help verify this one? If no timelines we can just fork - thank you!

**Review by lryong — APPROVED** [review]

**Comment by rynmccrmck** [comment]
@lryong thanks for review - I just realized that one of the sources.txt is now missing (and why were seeing so many subtractions to free domains). I'll see what I can do and update.

**Comment by rynmccrmck** [comment]
> @lryong thanks for review - I just realized that one of the sources.txt is now missing (and why were seeing so many subtractions to free domains). I'll see what I can do and update.

Actually this is free domains being renamed to disposable. If you have any opinion on this please let me know.

**Comment by lryong** [comment]
@rynmccrmck 
Thank you for following up on this issue, I double checked your PR and it seems that the data source you provided is not widely recognized.
 In order to provide a more reliable data source, we are not accepting your PR for now, but we are considering to provide an interface for users to add custom disposable domain or free domain, if you are interested, you are welcome to propose a PR as well!

**Pull request closed without merging**
